# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Elige tu propia revoluci√≥n
email: info[@]rizoma.fair.coop
description: Guia para el autoestopista galactico revolucionario
baseurl: "/etpr" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  CoopIntAr

# Build settings
markdown: kramdown
